parameters:
#    annonces_voitures.example.class: Annonces\VoituresBundle\Example

services:
#    annonces_voitures.example:
#        class: %annonces_voitures.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
